In [1]:
!wget -O amz-review-apparel.csv https://tinyurl.com/y3gfnlx2

--2020-08-10 23:24:38--  https://tinyurl.com/y3gfnlx2
Resolving tinyurl.com (tinyurl.com)... 104.20.138.65, 104.20.139.65, 172.67.1.225
Connecting to tinyurl.com (tinyurl.com)|104.20.138.65|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://recommendation-demo-yianc.s3.us-east-1.amazonaws.com/amz-review/amz-review-apparel.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIATLORAEYMTX7JY4ER%2F20200810%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200810T152347Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=e6c35dc78526ddb7cd7e913fa63c5f8a5ad57a39ca556ab68fe010ed58051435 [following]
--2020-08-10 23:24:39--  https://recommendation-demo-yianc.s3.us-east-1.amazonaws.com/amz-review/amz-review-apparel.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIATLORAEYMTX7JY4ER%2F20200810%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200810T152347Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=e6c35dc78526ddb7cd7

In [2]:
import pandas as pd 

user_item = './amz-review-apparel.csv'

user_item_df = pd.read_csv(user_item)
user_item_df.head()

customer_id  cnt marketplace  customer_id.1       review_id  product_id  \
0     28563435   13          US       28563435  R2M9YYZ4DLZRMN  B003OQTQ0W   
1     28563435   13          US       28563435  R2DIHSYWNP3FPJ  B0093O17U6   
2     28563435   13          US       28563435  R36XY86RBEESP6  B0051I6MYY   
3     28563435   13          US       28563435  R2X9GLV67VACAN  B005F29FKO   
4     28563435   13          US       28563435   RS4RG84BX2KK5  B004QF0THY   

   product_parent                                      product_title  \
0        97286984             Carhartt Men's Two-Tone Trifold Wallet   
1       765210786  IH Camouflage Trucker Cap in Mossy Oak Break-U...   
2       268391293      IH 5 Panel Trucker Cap with Liquid Metal Logo   
3       506334102  Carhartt Men's Relaxed Straight Denim Five Poc...   
4       206343191    Dickies Men's 2 Pack Wool Blend Boot Crew Socks   

   star_rating  helpful_votes  total_votes vine verified_purchase  \
0            5              0            0    N                 Y   
1            5              0            0    N                 Y   
2            5              1            1    N                 Y   
3            5              0            0    N                 Y   
4            5              0            0    N                 Y   

      review_headline                                        review_body  \
0  Outstanding Wallet  I have owned a lot of wallets over the years a...   
1           Great cap  This is a very nice hat,but i have got another...   
2        Great hat!!!  This is a great hat and is very well made!! I ...   
3         Great pants  I have always been a Wrangler man most of my l...   
4  Very Great socks!!  Wool is the only socks i wear and the only thi...   

  review_date  year  
0  2013-07-11  2013  
1  2013-05-11  2013  
2  2013-04-13  2013  
3  2012-12-08  2012  
4  2012-12-08  2012

In [4]:
import sys
sys.path.append('../')

from preprocessing.amz_datareader import AMZDataReader
from preprocessing.factorization_machine_transformer import  FactorizationMachineTransformer


user_item = './amz-review-apparel.csv'
reader = AMZDataReader()
user_item  = reader.read_user_item_rating(user_item)
users = {}
items = {}
train_user_item = user_item[:int(len(user_item)*0.8)]
test_user_item = user_item[int(len(user_item)*0.8):]
transformer = FactorizationMachineTransformer(users, items, train_user_item)
X_train, Y_train, nFeatures, processed = transformer.get_feature_vectors(users, items, train_user_item)
X_test, Y_test, nFeatures, processed = transformer.get_feature_vectors(users, items, test_user_item)

In [ ]:
#create bucket! 

In [5]:
bucket = 'recommendation-demo-yianc'
prefix = 'sagemaker/fm-amz'
train_key      = 'train.protobuf'
train_prefix   = '{}/{}'.format(prefix, 'train')
test_key       = 'test.protobuf'
test_prefix    = '{}/{}/'.format(prefix, 'test')
output_prefix  = 's3://{}/{}/output'.format(bucket, prefix)

def writeDatasetToProtobuf(X, Y, bucket, prefix, key):
    import io,boto3
    import sagemaker.amazon.common as smac
    buf = io.BytesIO()
    smac.write_spmatrix_to_sparse_tensor(buf, X, Y)
    buf.seek(0)
    print(buf)
    obj = '{}/{}'.format(prefix, key)
    boto3.resource('s3').Bucket(bucket).Object(obj).upload_fileobj(buf)
    return 's3://{}/{}'.format(bucket,obj)
 
    
train_data = writeDatasetToProtobuf(X_train, Y_train, bucket, train_prefix, train_key)    
  
print('Output: {}'.format(output_prefix))

Output: s3://recommendation-demo-yianc/sagemaker/fm-amz/output


In [6]:
train_data 

's3://recommendation-demo-yianc/sagemaker/fm-amz/train/train.protobuf'

In [7]:
import sagemaker 

container = sagemaker.image_uris.retrieve(framework='factorization-machines', region='us-east-1', version='latest')
container 


Defaulting to the only supported framework/algorithm version: 1. Ignoring framework/algorithm version: latest.


'382416733822.dkr.ecr.us-east-1.amazonaws.com/factorization-machines:1'

In [8]:

from sagemaker import get_execution_role

import boto3 

region = boto3.Session().region_name
crole = 'AmazonSageMaker-ExecutionRole-20200603T105247'

print(sagemaker.estimator.Estimator)
fm = sagemaker.estimator.Estimator(image_uri=container,
                                   role=crole, 
                                   instance_count=1, 
                                   instance_type='ml.c4.xlarge',
                                   output_path=output_prefix,
                                   sagemaker_session=sagemaker.Session())



fm.set_hyperparameters(
                      feature_dim=nFeatures,
                      predictor_type='regressor',
                      mini_batch_size=1000,
                      num_factors=64,
                      epochs=50)

fm.fit({'train': train_data})


<class 'sagemaker.estimator.Estimator'>
2020-08-10 16:07:10 Starting - Starting the training job...
2020-08-10 16:07:13 Starting - Launching requested ML instances......
2020-08-10 16:08:30 Starting - Preparing the instances for training......
2020-08-10 16:10:00 Downloading - Downloading input data
2020-08-10 16:10:00 Training - Downloading the training image...
2020-08-10 16:10:19 Training - Training image download completed. Training in progress.Docker entrypoint called with argument(s): train
Running default environment configuration script
/opt/amazon/lib/python2.7/site-packages/pandas/util/nosetester.py:13: DeprecationWarning: Importing from numpy.testing.nosetester is deprecated, import from numpy.testing instead.
  from numpy.testing import nosetester
[08/10/2020 16:10:21 INFO 140371927496512] Reading default configuration from /opt/amazon/lib/python2.7/site-packages/algorithm/resources/default-conf.json: {u'factors_lr': u'0.0001', u'linear_init_sigma': u'0.01', u'epochs': 1, u

[08/10/2020 16:11:02 INFO 140371927496512] Iter[1] Batch [1000]#011Speed: 60270.78 samples/sec
[08/10/2020 16:11:02 INFO 140371927496512] #quality_metric: host=algo-1, epoch=1, batch=1000 train rmse <loss>=1.13156762712
[08/10/2020 16:11:02 INFO 140371927496512] #quality_metric: host=algo-1, epoch=1, batch=1000 train mse <loss>=1.28044529476
[08/10/2020 16:11:02 INFO 140371927496512] #quality_metric: host=algo-1, epoch=1, batch=1000 train absolute_loss <loss>=0.908872272991
[2020-08-10 16:11:07.843] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 4, "duration": 21630, "num_examples": 1300, "num_bytes": 87782072}
[08/10/2020 16:11:07 INFO 140371927496512] #quality_metric: host=algo-1, epoch=1, train rmse <loss>=1.13626978956
[08/10/2020 16:11:07 INFO 140371927496512] #quality_metric: host=algo-1, epoch=1, train mse <loss>=1.29110903466
[08/10/2020 16:11:07 INFO 140371927496512] #quality_metric: host=algo-1, epoch=1, train absolute_loss <loss>=0.91135

[08/10/2020 16:11:59 INFO 140371927496512] Iter[4] Batch [500]#011Speed: 61005.55 samples/sec
[08/10/2020 16:11:59 INFO 140371927496512] #quality_metric: host=algo-1, epoch=4, batch=500 train rmse <loss>=1.10731543386
[08/10/2020 16:11:59 INFO 140371927496512] #quality_metric: host=algo-1, epoch=4, batch=500 train mse <loss>=1.22614747007
[08/10/2020 16:11:59 INFO 140371927496512] #quality_metric: host=algo-1, epoch=4, batch=500 train absolute_loss <loss>=0.883896595968
[08/10/2020 16:12:07 INFO 140371927496512] Iter[4] Batch [1000]#011Speed: 60641.53 samples/sec
[08/10/2020 16:12:07 INFO 140371927496512] #quality_metric: host=algo-1, epoch=4, batch=1000 train rmse <loss>=1.0941937776
[08/10/2020 16:12:07 INFO 140371927496512] #quality_metric: host=algo-1, epoch=4, batch=1000 train mse <loss>=1.19726002294
[08/10/2020 16:12:07 INFO 140371927496512] #quality_metric: host=algo-1, epoch=4, batch=1000 train absolute_loss <loss>=0.871839779422
[2020-08-10 16:12:12.144] [tensorio] [info] epo

[08/10/2020 16:13:03 INFO 140371927496512] Iter[7] Batch [500]#011Speed: 60312.23 samples/sec
[08/10/2020 16:13:03 INFO 140371927496512] #quality_metric: host=algo-1, epoch=7, batch=500 train rmse <loss>=1.07603093351
[08/10/2020 16:13:03 INFO 140371927496512] #quality_metric: host=algo-1, epoch=7, batch=500 train mse <loss>=1.15784256987
[08/10/2020 16:13:03 INFO 140371927496512] #quality_metric: host=algo-1, epoch=7, batch=500 train absolute_loss <loss>=0.854443522257
[08/10/2020 16:13:11 INFO 140371927496512] Iter[7] Batch [1000]#011Speed: 61000.85 samples/sec
[08/10/2020 16:13:11 INFO 140371927496512] #quality_metric: host=algo-1, epoch=7, batch=1000 train rmse <loss>=1.06251687786
[08/10/2020 16:13:11 INFO 140371927496512] #quality_metric: host=algo-1, epoch=7, batch=1000 train mse <loss>=1.12894211575
[08/10/2020 16:13:11 INFO 140371927496512] #quality_metric: host=algo-1, epoch=7, batch=1000 train absolute_loss <loss>=0.841119380071
[2020-08-10 16:13:16.341] [tensorio] [info] ep

[08/10/2020 16:14:15 INFO 140371927496512] Iter[10] Batch [1000]#011Speed: 60432.05 samples/sec
[08/10/2020 16:14:15 INFO 140371927496512] #quality_metric: host=algo-1, epoch=10, batch=1000 train rmse <loss>=1.03507495516
[08/10/2020 16:14:15 INFO 140371927496512] #quality_metric: host=algo-1, epoch=10, batch=1000 train mse <loss>=1.07138016281
[08/10/2020 16:14:15 INFO 140371927496512] #quality_metric: host=algo-1, epoch=10, batch=1000 train absolute_loss <loss>=0.815169242623
[2020-08-10 16:14:20.718] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 22, "duration": 21571, "num_examples": 1300, "num_bytes": 87782072}
[08/10/2020 16:14:20 INFO 140371927496512] #quality_metric: host=algo-1, epoch=10, train rmse <loss>=1.03997401874
[08/10/2020 16:14:20 INFO 140371927496512] #quality_metric: host=algo-1, epoch=10, train mse <loss>=1.08154595966
[08/10/2020 16:14:20 INFO 140371927496512] #quality_metric: host=algo-1, epoch=10, train absolute_loss <loss>

[08/10/2020 16:15:11 INFO 140371927496512] Iter[13] Batch [500]#011Speed: 61190.35 samples/sec
[08/10/2020 16:15:11 INFO 140371927496512] #quality_metric: host=algo-1, epoch=13, batch=500 train rmse <loss>=1.02455248957
[08/10/2020 16:15:11 INFO 140371927496512] #quality_metric: host=algo-1, epoch=13, batch=500 train mse <loss>=1.04970780387
[08/10/2020 16:15:11 INFO 140371927496512] #quality_metric: host=algo-1, epoch=13, batch=500 train absolute_loss <loss>=0.806628182843
[08/10/2020 16:15:19 INFO 140371927496512] Iter[13] Batch [1000]#011Speed: 61678.70 samples/sec
[08/10/2020 16:15:19 INFO 140371927496512] #quality_metric: host=algo-1, epoch=13, batch=1000 train rmse <loss>=1.01020307899
[08/10/2020 16:15:19 INFO 140371927496512] #quality_metric: host=algo-1, epoch=13, batch=1000 train mse <loss>=1.0205102608
[08/10/2020 16:15:19 INFO 140371927496512] #quality_metric: host=algo-1, epoch=13, batch=1000 train absolute_loss <loss>=0.791761823565
[2020-08-10 16:15:24.558] [tensorio] [i

[08/10/2020 16:16:15 INFO 140371927496512] Iter[16] Batch [500]#011Speed: 60276.13 samples/sec
[08/10/2020 16:16:15 INFO 140371927496512] #quality_metric: host=algo-1, epoch=16, batch=500 train rmse <loss>=1.00164524566
[08/10/2020 16:16:15 INFO 140371927496512] #quality_metric: host=algo-1, epoch=16, batch=500 train mse <loss>=1.00329319815
[08/10/2020 16:16:15 INFO 140371927496512] #quality_metric: host=algo-1, epoch=16, batch=500 train absolute_loss <loss>=0.78504321484
[08/10/2020 16:16:24 INFO 140371927496512] Iter[16] Batch [1000]#011Speed: 61071.04 samples/sec
[08/10/2020 16:16:24 INFO 140371927496512] #quality_metric: host=algo-1, epoch=16, batch=1000 train rmse <loss>=0.987050466772
[08/10/2020 16:16:24 INFO 140371927496512] #quality_metric: host=algo-1, epoch=16, batch=1000 train mse <loss>=0.974268623954
[08/10/2020 16:16:24 INFO 140371927496512] #quality_metric: host=algo-1, epoch=16, batch=1000 train absolute_loss <loss>=0.769883394255
[2020-08-10 16:16:29.003] [tensorio] 

[08/10/2020 16:17:20 INFO 140371927496512] Iter[19] Batch [500]#011Speed: 60054.44 samples/sec
[08/10/2020 16:17:20 INFO 140371927496512] #quality_metric: host=algo-1, epoch=19, batch=500 train rmse <loss>=0.979883027206
[08/10/2020 16:17:20 INFO 140371927496512] #quality_metric: host=algo-1, epoch=19, batch=500 train mse <loss>=0.960170747007
[08/10/2020 16:17:20 INFO 140371927496512] #quality_metric: host=algo-1, epoch=19, batch=500 train absolute_loss <loss>=0.764363294773
[08/10/2020 16:17:28 INFO 140371927496512] Iter[19] Batch [1000]#011Speed: 60827.01 samples/sec
[08/10/2020 16:17:28 INFO 140371927496512] #quality_metric: host=algo-1, epoch=19, batch=1000 train rmse <loss>=0.965162969457
[08/10/2020 16:17:28 INFO 140371927496512] #quality_metric: host=algo-1, epoch=19, batch=1000 train mse <loss>=0.93153955761
[08/10/2020 16:17:28 INFO 140371927496512] #quality_metric: host=algo-1, epoch=19, batch=1000 train absolute_loss <loss>=0.749093065077
[2020-08-10 16:17:33.448] [tensorio

[08/10/2020 16:18:24 INFO 140371927496512] Iter[22] Batch [500]#011Speed: 60033.63 samples/sec
[08/10/2020 16:18:24 INFO 140371927496512] #quality_metric: host=algo-1, epoch=22, batch=500 train rmse <loss>=0.959020079624
[08/10/2020 16:18:24 INFO 140371927496512] #quality_metric: host=algo-1, epoch=22, batch=500 train mse <loss>=0.919719513122
[08/10/2020 16:18:24 INFO 140371927496512] #quality_metric: host=algo-1, epoch=22, batch=500 train absolute_loss <loss>=0.744445897512
[08/10/2020 16:18:33 INFO 140371927496512] Iter[22] Batch [1000]#011Speed: 60775.65 samples/sec
[08/10/2020 16:18:33 INFO 140371927496512] #quality_metric: host=algo-1, epoch=22, batch=1000 train rmse <loss>=0.944279166244
[08/10/2020 16:18:33 INFO 140371927496512] #quality_metric: host=algo-1, epoch=22, batch=1000 train mse <loss>=0.891663143802
[08/10/2020 16:18:33 INFO 140371927496512] #quality_metric: host=algo-1, epoch=22, batch=1000 train absolute_loss <loss>=0.729191129732
[2020-08-10 16:18:37.991] [tensori

[08/10/2020 16:19:28 INFO 140371927496512] Iter[25] Batch [500]#011Speed: 60977.35 samples/sec
[08/10/2020 16:19:28 INFO 140371927496512] #quality_metric: host=algo-1, epoch=25, batch=500 train rmse <loss>=0.938911140512
[08/10/2020 16:19:28 INFO 140371927496512] #quality_metric: host=algo-1, epoch=25, batch=500 train mse <loss>=0.881554129778
[08/10/2020 16:19:28 INFO 140371927496512] #quality_metric: host=algo-1, epoch=25, batch=500 train absolute_loss <loss>=0.72521514588
[08/10/2020 16:19:37 INFO 140371927496512] Iter[25] Batch [1000]#011Speed: 61612.38 samples/sec
[08/10/2020 16:19:37 INFO 140371927496512] #quality_metric: host=algo-1, epoch=25, batch=1000 train rmse <loss>=0.92423767263
[08/10/2020 16:19:37 INFO 140371927496512] #quality_metric: host=algo-1, epoch=25, batch=1000 train mse <loss>=0.854215275508
[08/10/2020 16:19:37 INFO 140371927496512] #quality_metric: host=algo-1, epoch=25, batch=1000 train absolute_loss <loss>=0.710071711309
[2020-08-10 16:19:41.878] [tensorio]

[08/10/2020 16:20:32 INFO 140371927496512] Iter[28] Batch [500]#011Speed: 60348.76 samples/sec
[08/10/2020 16:20:32 INFO 140371927496512] #quality_metric: host=algo-1, epoch=28, batch=500 train rmse <loss>=0.919464105985
[08/10/2020 16:20:32 INFO 140371927496512] #quality_metric: host=algo-1, epoch=28, batch=500 train mse <loss>=0.845414242194
[08/10/2020 16:20:32 INFO 140371927496512] #quality_metric: host=algo-1, epoch=28, batch=500 train absolute_loss <loss>=0.706632534735
[08/10/2020 16:20:40 INFO 140371927496512] Iter[28] Batch [1000]#011Speed: 60796.27 samples/sec
[08/10/2020 16:20:40 INFO 140371927496512] #quality_metric: host=algo-1, epoch=28, batch=1000 train rmse <loss>=0.90493196334
[08/10/2020 16:20:40 INFO 140371927496512] #quality_metric: host=algo-1, epoch=28, batch=1000 train mse <loss>=0.818901858274
[08/10/2020 16:20:40 INFO 140371927496512] #quality_metric: host=algo-1, epoch=28, batch=1000 train absolute_loss <loss>=0.691675576133
[2020-08-10 16:20:45.907] [tensorio

[08/10/2020 16:21:37 INFO 140371927496512] Iter[31] Batch [500]#011Speed: 60916.34 samples/sec
[08/10/2020 16:21:37 INFO 140371927496512] #quality_metric: host=algo-1, epoch=31, batch=500 train rmse <loss>=0.900616476699
[08/10/2020 16:21:37 INFO 140371927496512] #quality_metric: host=algo-1, epoch=31, batch=500 train mse <loss>=0.811110038103
[08/10/2020 16:21:37 INFO 140371927496512] #quality_metric: host=algo-1, epoch=31, batch=500 train absolute_loss <loss>=0.688671250882
[08/10/2020 16:21:45 INFO 140371927496512] Iter[31] Batch [1000]#011Speed: 61254.36 samples/sec
[08/10/2020 16:21:45 INFO 140371927496512] #quality_metric: host=algo-1, epoch=31, batch=1000 train rmse <loss>=0.886287090942
[08/10/2020 16:21:45 INFO 140371927496512] #quality_metric: host=algo-1, epoch=31, batch=1000 train mse <loss>=0.78550480757
[08/10/2020 16:21:45 INFO 140371927496512] #quality_metric: host=algo-1, epoch=31, batch=1000 train absolute_loss <loss>=0.673959239125
[2020-08-10 16:21:50.149] [tensorio

Training seconds: 1148
Billable seconds: 1148


In [9]:
fm_predictor = fm.deploy(instance_type='ml.c4.xlarge', initial_instance_count=1)


---------------!

In [10]:
from sagemaker.serializers import BaseSerializer
import json 

class FMSerializer(BaseSerializer): 
    CONTENT_TYPE='application/json'
    def serialize(self, data):
        js = {'instances': []}
        for row in data:
            js['instances'].append({'features': row.tolist()})
        #print js
        return json.dumps(js)

fm_predictor.serializer = FMSerializer()
fm_predictor.deserializer = sagemaker.deserializers.JSONDeserializer()


In [12]:
# from sklearn.metrics import mean_squared_error
import numpy 

X_test_arr = X_test[:100].toarray(order='C')
print(X_test_arr)

result = fm_predictor.predict(X_test_arr) 
y_pred = [] 
for p in result['predictions']: 
    y_pred.append(p['score'])

rmse = numpy.sqrt(numpy.mean((y_pred-Y_test[:100])**2))


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://runtime.sagemaker.us-east-1.amazonaws.com/endpoints/factorization-machines-2020-08-10-22-13-03-380/invocations".

In [ ]:
rmse

iid  uid  rating  timestamp                          title  \
46289  244    3       5  880602451  Smilla's Sense of Snow (1997)   
46290   62    3       3  879372325                Stargate (1994)   
46291  286    3       2  876522316    English Patient, The (1996)   
46292  303    3       3  879485184             Ulee's Gold (1997)   
46293  291    3       3  874833936          Absolute Power (1997)   
...    ...  ...     ...        ...                            ...   
46374  916    3       3  880843838           Lost in Space (1998)   
46375  910    3       2  881421019            Nil By Mouth (1997)   
46376  923    3       4  880387707   Raise the Red Lantern (1991)   
46377  917    3       1  882911567          Mercury Rising (1998)   
46378  936    3       4  886833148             Brassed Off (1996)   

      release_date  video_release_date  \
46289  14-Mar-1997                 NaN   
46290  01-Jan-1994                 NaN   
46291  15-Nov-1996                 NaN   
46292  01-Jan-1997                 NaN   
46293  14-Feb-1997                 NaN   
...            ...                 ...   
46374  27-Mar-1998                 NaN   
46375  06-Feb-1998                 NaN   
46376  01-Jan-1991                 NaN   
46377  27-Mar-1998                 NaN   
46378  13-Jun-1997                 NaN   

                                                imdb url  unknown  Action  \
46289  http://us.imdb.com/M/title-exact?Smilla%27s%20...        0       1   
46290  http://us.imdb.com/M/title-exact?Stargate%20(1...        0       1   
46291  http://us.imdb.com/M/title-exact?English%20Pat...        0       0   
46292  http://us.imdb.com/M/title-exact?Ulee%27s+Gold...        0       0   
46293  http://us.imdb.com/M/title-exact?Absolute%20Po...        0       0   
...                                                  ...      ...     ...   
46374      http://us.imdb.com/Title?Lost+in+Space+(1998)        0       1   
46375       http://us.imdb.com/Title?Nil+By+Mouth+(1997)        0       0   
46376  http://us.imdb.com/M/title-exact?Da%20Hong%20D...        0       0   
46377     http://us.imdb.com/Title?Mercury+Rising+(1998)        0       1   
46378  http://us.imdb.com/M/title-exact?Brassed%20Off...        0       0   

       ...  Romance  Sci-Fi  Thriller  War  Western  age  gender  occupation  \
46289  ...        0       0         1    0        0   23       M      writer   
46290  ...        0       1         0    0        0   23       M      writer   
46291  ...        1       0         0    1        0   23       M      writer   
46292  ...        0       0         0    0        0   23       M      writer   
46293  ...        0       0         1    0        0   23       M      writer   
...    ...      ...     ...       ...  ...      ...  ...     ...         ...   
46374  ...        0       1         1    0        0   23       M      writer   
46375  ...        0       0         0    0        0   23       M      writer   
46376  ...        0       0         0    0        0   23       M      writer   
46377  ...        0       0         1    0        0   23       M      writer   
46378  ...        1       0         0    0        0   23       M      writer   

       zipcode  age_segment  
46289    32067            2  
46290    32067            2  
46291    32067            2  
46292    32067            2  
46293    32067            2  
...        ...          ...  
46374    32067            2  
46375    32067            2  
46376    32067            2  
46377    32067            2  
46378    32067            2  

[90 rows x 32 columns]